@echo off

cd /d %~dp0

echo.
call code --install-extension aaron-bond.better-comments
call code --install-extension alefragnani.Bookmarks
call code --install-extension alefragnani.project-manager
call code --install-extension aliariff.vscode-erb-beautify
call code --install-extension amazonwebservices.aws-toolkit-vscode
call code --install-extension arcanis.vscode-zipfs
call code --install-extension benspaulding.procfile
call code --install-extension burkeholland.simple-react-snippets
call code --install-extension capaj.vscode-standardjs-snippets
call code --install-extension castwide.ruby-debug
call code --install-extension castwide.solargraph
call code --install-extension christian-kohler.npm-intellisense
call code --install-extension christian-kohler.path-intellisense
call code --install-extension codezombiech.gitignore
call code --install-extension Compulim.compulim-vscode-closetag
call code --install-extension DavidAnson.vscode-markdownlint
call code --install-extension dbaeumer.jshint
call code --install-extension dbaeumer.vscode-eslint
call code --install-extension declanzou.index-generator
call code --install-extension deque-systems.vscode-axe-linter
call code --install-extension dongido.sync-env
call code --install-extension donjayamanne.git-extension-pack
call code --install-extension donjayamanne.githistory
call code --install-extension dotenv.dotenv-vscode
call code --install-extension dozerg.tsimportsorter
call code --install-extension dracula-theme.theme-dracula
call code --install-extension eamodio.gitlens
call code --install-extension EditorConfig.EditorConfig
call code --install-extension esbenp.prettier-vscode
call code --install-extension felipecaputo.git-project-manager
call code --install-extension firefox-devtools.vscode-firefox-debug
call code --install-extension flowtype.flow-for-vscode
call code --install-extension formulahendry.auto-close-tag
call code --install-extension formulahendry.auto-rename-tag
call code --install-extension formulahendry.code-runner
call code --install-extension GitHub.github-vscode-theme
call code --install-extension github.vscode-pull-request-github
call code --install-extension glenn2223.live-sass
call code --install-extension googlecloudtools.cloudcode
call code --install-extension GrapeCity.gc-excelviewer
call code --install-extension groksrc.ruby
call code --install-extension Gruntfuggly.todo-tree
call code --install-extension hoovercj.ruby-linter
call code --install-extension humao.rest-client
call code --install-extension IronGeek.vscode-env
call code --install-extension itarato.byesig
call code --install-extension ivangabriele.vscode-heroku
call code --install-extension JayFong.generate-index
call code --install-extension jbockle.jbockle-format-files
call code --install-extension jnbt.vscode-rufo
call code --install-extension joy-yu.css-snippets
call code --install-extension jtr.vscode-position
call code --install-extension joostlubach.js-index
call code --install-extension kaiwood.endwise
call code --install-extension kingdaro.generate-index
call code --install-extension koichisasada.vscode-rdbg
call code --install-extension lacroixdavid1.vscode-format-context-menu
call code --install-extension logerfo.procfile-support
call code --install-extension mark-tucker.aws-cli-configure
call code --install-extension maxcutlyp.dotenv-autocomplete
call code --install-extension mechatroner.rainbow-csv
call code --install-extension mgmcdermott.vscode-language-babel
call code --install-extension mhutchie.git-graph
call code --install-extension miguel-savignano.ruby-symbols
call code --install-extension mike-co.import-sorter
call code --install-extension mikestead.dotenv
call code --install-extension mindaro-dev.file-downloader
call code --install-extension mindaro.mindaro
call code --install-extension misogi.ruby-rubocop
call code --install-extension mohsen1.react-javascript-to-typescript-transform-vscode
call code --install-extension ms-azuretools.vscode-azureappservice
call code --install-extension ms-azuretools.vscode-docker
call code --install-extension MS-CEINTL.vscode-language-pack-ru
call code --install-extension ms-dotnettools.csharp
call code --install-extension ms-edgedevtools.vscode-edge-devtools
call code --install-extension ms-kubernetes-tools.vscode-kubernetes-tools
call code --install-extension ms-mssql.data-workspace-vscode
call code --install-extension ms-mssql.mssql
call code --install-extension ms-mssql.sql-bindings-vscode
call code --install-extension ms-mssql.sql-database-projects-vscode
call code --install-extension ms-vscode-remote.remote-containers
call code --install-extension ms-vscode-remote.remote-ssh
call code --install-extension ms-vscode-remote.remote-ssh-edit
call code --install-extension ms-vscode-remote.remote-wsl
call code --install-extension ms-vscode-remote.vscode-remote-extensionpack
call code --install-extension ms-vscode.azure-account
call code --install-extension ms-vscode.hexeditor
call code --install-extension ms-vscode.notepadplusplus-keybindings
call code --install-extension ms-vscode.powershell
call code --install-extension ms-vscode.vscode-typescript-next
call code --install-extension mscolnick.export-typescript
call code --install-extension NathanRidley.autotrim
call code --install-extension natqe.reload
call code --install-extension Nixon.env-cmd-file-syntax
call code --install-extension NuclleaR.vscode-extension-auto-import
call code --install-extension octref.vetur
call code --install-extension oderwat.indent-rainbow
call code --install-extension Orta.vscode-jest
call code --install-extension PKief.material-icon-theme
call code --install-extension pkosta2005.heroku-command
call code --install-extension rebornix.ruby
call code --install-extension redhat.vscode-xml
call code --install-extension redhat.vscode-yaml
call code --install-extension ritwickdey.LiveServer
call code --install-extension robole.markdown-snippets
call code --install-extension robole.marky-dynamic
call code --install-extension robole.marky-edit
call code --install-extension robole.marky-markdown
call code --install-extension robole.marky-stats
call code --install-extension rvest.vs-code-prettier-eslint
call code --install-extension samverschueren.linter-xo
call code --install-extension sarahridge.vscode-ruby-syntax
call code --install-extension Shan.code-settings-sync
call code --install-extension shardulm94.trailing-spaces
call code --install-extension shd101wyy.markdown-preview-enhanced
call code --install-extension shopify.ruby-extensions-pack
call code --install-extension shopify.ruby-lsp
call code --install-extension shopify.vscode-shadowenv
call code --install-extension sidthesloth.html5-boilerplate
call code --install-extension sorbet.sorbet-vscode-extension
call code --install-extension sourcegraph.sourcegraph
call code --install-extension sourcegraph.vscode-sourcegraph-theme
call code --install-extension standard.vscode-standard
call code --install-extension steoates.autoimport
call code --install-extension streetsidesoftware.code-spell-checker
call code --install-extension streetsidesoftware.code-spell-checker-russian
call code --install-extension streetsidesoftware.code-spell-checker-ukrainian
call code --install-extension stringham.move-ts
call code --install-extension stylelint.vscode-stylelint
call code --install-extension sunjw.jstool
call code --install-extension svipas.code-autocomplete
call code --install-extension tabnine.tabnine-vscode
call code --install-extension temitope1909.dotenv-intellisense
call code --install-extension TimonVS.ReactSnippetsStandard
call code --install-extension tsugitta.create-index
call code --install-extension Tyriar.lorem-ipsum
call code --install-extension unifiedjs.vscode-mdx
call code --install-extension unifiedjs.vscode-remark
call code --install-extension unional.vscode-sort-package-json
call code --install-extension vayan.haml
call code --install-extension VisualStudioExptTeam.intellicode-api-usage-examples
call code --install-extension VisualStudioExptTeam.vscodeintellicode
call code --install-extension vscode-icons-team.vscode-icons
call code --install-extension wayou.vscode-todo-highlight
call code --install-extension wingrunr21.vscode-ruby
call code --install-extension wix.vscode-import-cost
call code --install-extension xabikos.JavaScriptSnippets
call code --install-extension xyc.vscode-mdx-preview
call code --install-extension yzhang.markdown-all-in-one
call code --install-extension ziyasal.vscode-open-in-github

echo.
pause
